#!/bin/bash
#set -e

LOGFILE=/home/opc/CLOUD-INIT.log

### Send stdout, stderr to /var/log/messages/
exec 1> >(logger -s -t $(basename $0)) 2>&1

echo "`/bin/date` : START of cloud-init script" > $LOGFILE 2>&1

### Storage setup
wget -O /usr/local/bin/iscsiattach.sh https://raw.githubusercontent.com/oracle/terraform-provider-oci/master/docs/examples/storage/nfs/userdata/iscsiattach.sh
chmod +x /usr/local/bin/iscsiattach.sh
/usr/local/bin/iscsiattach.sh
mkfs.xfs /dev/sdb		# mkfs.xfs -f /dev/sdb if you want to override existing filesystem
mkdir /mnt/data1
mount -t xfs /dev/sdb /mnt/data1
sdb_uuid=`blkid /dev/sdb -s UUID -o value`
echo "UUID=$sdb_uuid    /mnt/data1    xfs    defaults,noatime,_netdev,nofail" >> /etc/fstab
chown opc:opc /mnt/data1

### install and configure NFS Server
yum install -y nfs-utils
echo "/mnt/data1 10.0.1.0/24(sync)" >> /etc/exports
firewall-offline-cmd  --permanent --add-service=nfs
systemctl restart firewalld
systemctl enable nfs-server
systemctl start nfs-server
exportfs -a

### YUM update
yum update -y

echo "`/bin/date` : END of cloud-init script" >> $LOGFILE 2>&1

### reboot to finish yum update
reboot



